description "Kerrigan Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env KERRIGAND_BIN="/usr/bin/kerrigand"
env KERRIGAND_USER="kerrigan"
env KERRIGAND_GROUP="kerrigan"
env KERRIGAND_PIDDIR="/var/run/kerrigand"
# upstart can't handle variables constructed with other variables
env KERRIGAND_PIDFILE="/var/run/kerrigand/kerrigand.pid"
env KERRIGAND_CONFIGFILE="/etc/kerrigan/kerrigan.conf"
env KERRIGAND_DATADIR="/var/lib/kerrigand"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # kerrigand will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$KERRIGAND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run kerrigand."
        echo "The setting must appear in $KERRIGAND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Kerrigan Core Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$KERRIGAND_PIDDIR"
    chmod 0755 "$KERRIGAND_PIDDIR"
    chown $KERRIGAND_USER:$KERRIGAND_GROUP "$KERRIGAND_PIDDIR"
    chown $KERRIGAND_USER:$KERRIGAND_GROUP "$KERRIGAND_CONFIGFILE"
    chmod 0660 "$KERRIGAND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$KERRIGAND_PIDFILE" \
    --chuid $KERRIGAND_USER:$KERRIGAND_GROUP \
    --exec "$KERRIGAND_BIN" \
    -- \
    -pid="$KERRIGAND_PIDFILE" \
    -conf="$KERRIGAND_CONFIGFILE" \
    -datadir="$KERRIGAND_DATADIR" \
    -disablewallet \
    -daemon
